In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler,OneHotEncoder,LabelEncoder
import pickle 
import tensorflow

In [2]:
data = pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
data = data.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [4]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [5]:
label_encoder = LabelEncoder()
data['Gender'] = label_encoder.fit_transform(data['Gender'])

In [6]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [7]:
geo_encoder = OneHotEncoder(sparse_output=False)

In [8]:
geo = geo_encoder.fit_transform(data[['Geography']])

In [9]:
geo

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]], shape=(10000, 3))

In [10]:
geo_df = pd.DataFrame(geo,columns=geo_encoder.get_feature_names_out(['Geography']))

In [11]:
geo_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [12]:
data = pd.concat([data.drop('Geography',axis=1),geo_df],axis=1)

In [13]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [14]:
x = data.drop('EstimatedSalary',axis=1)
y = data['EstimatedSalary']

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [16]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [17]:
with open('Reg_gender.pkl','wb') as file:
    pickle.dump(label_encoder,file)
with open('Reg_geo.pkl','wb') as file:
    pickle.dump(geo_encoder,file)
with open('Reg_scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

In [ ]:

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard

In [ ]:
model = Sequential([
    Dense(64,activation='relu',input_shape=(x_train.shape[1],)),
    Dense(32,activation='relu'),
    Dense(1,activation='sigmoid')
])
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])

model.summary()

c:\Users\DHRUV\Desktop\Dhruv\Study\Machine_Learning\Python\venv\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [20]:
import datetime
log_dir = 'reg/fit'+datetime.datetime.now().strftime("%Y/%m/%d, %H:%M:%S")
tensorboard_callback = TensorBoard(log_dir = log_dir,histogram_freq=1)

In [21]:
early_stopping_callback = EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [ ]:
import datetime

log_dir = "reg/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = tf.keras.callbacks.TensorBoard(
    log_dir=log_dir,
    histogram_freq=1,        
    write_graph=True,     
    write_images=True,      
    update_freq='epoch',    
    profile_batch=0,        
    embeddings_freq=1   
)


history = model.fit(
    x_train, y_train,
    validation_data=(x_test, y_test),
    epochs=100,
    callbacks=[early_stopping_callback, tensorboard_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 100390.1953 - mae: 100390.1953 - val_loss: 98561.4609 - val_mae: 98561.4609
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 99770.3438 - mae: 99770.3438 - val_loss: 97285.7500 - val_mae: 97285.7500
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 97532.8906 - mae: 97532.8906 - val_loss: 93974.3906 - val_mae: 93974.3906
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 93023.4609 - mae: 93023.4609 - val_loss: 88271.8672 - val_mae: 88271.8672
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 86291.3516 - mae: 86291.3516 - val_loss: 80684.1328 - val_mae: 80684.1328
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 78054.4375 - mae: 78054.4375 - val_loss: 72342.6953 - val_mae: 72342.6953
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 69532.0703 - mae: 69532.0703 - val_loss: 64458.3984 - val_mae: 64458.3984
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 62026.0234 - mae: 62026.0234 - val_loss: 58216.0117 - val_mae: 58216.0117
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 56570.8242 - mae: 56570.8242 - val_loss: 54148.0234 - val_mae: 54148.0234
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 53203.4531 - mae: 53203.4531 - val_loss: 51929.5703 - val_mae: 51929.5703
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 51454.3906 - mae: 51454.3906 - val_loss: 51066.6211 - val_mae: 51066.6211
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50706.2969 - mae: 50706.2969 - val_loss: 50758.4531 - val_mae: 50758.4531
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50383.2891 - mae: 50383.2891 - val_loss: 50634.3281 - val_mae: 50634.3281
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50219.7656 - mae: 50219.7656 - val_loss: 50567.1484 - val_mae: 50567.1484
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50138.8867 - mae: 50138.8867 - val_loss: 50525.3516 - val_mae: 50525.3516
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50075.8594 - mae: 50075.8594 - val_loss: 50494.8125 - val_mae: 50494.8125
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50030.5117 - mae: 50030.5117 - val_loss: 50464.9102 - val_mae: 50464.9102
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49991.1094 - mae: 49991.1094 - val_loss: 50443.7656 - val_mae: 50443.7656
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49948.8125 - mae: 49948.8125 - val_loss: 50417.1953 - val_mae: 50417.1953
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49917.0781 - mae: 49917.0781 - val_loss: 50402.0430 - val_mae: 50402.0430
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49881.8242 - mae: 49881.8242 - val_loss: 50392.9062 - val_mae: 50392.9062
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49856.2344 - mae: 49856.2344 - val_loss: 50377.4883 - val_mae: 50377.4883
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49828.3086 - mae: 49828.3086 - val_loss: 50375.9375 - val_mae: 50375.9375
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49806.7344 - mae: 49806.7344 - val_loss: 50358.9648 - val_mae: 50358.9648
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49781.6836 - mae: 49781.6836 - val_loss: 50358.0547 - val_mae: 50358.0547
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49763.5664 - mae: 49763.5664 - val_loss: 50353.8047 - val_mae: 50353.8047
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49743.1914 - mae: 49743.1914 - val_loss: 50343.7031 - val_mae: 50343.7031
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49725.7539 - mae: 49725.7539 - val_loss: 50338.7109 - val_mae: 50338.7109
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49707.3047 - mae: 49707.3047 - val_loss: 50332.4336 - val_mae: 50332.4336
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49687.3828 - mae: 49687.3828 - val_loss: 50332.6875 - val_mae: 50332.6875
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49670.7891 - mae: 49670.7891 - val_loss: 50320.9062 - val_mae: 50320.9062
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49657.7070 - mae: 49657.7070 - val_loss: 50328.9844 - val_mae: 50328.9844
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49641.2344 - mae: 49641.2344 - val_loss: 50319.4688 - val_mae: 50319.4688
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49631.1328 - mae: 49631.1328 - val_loss: 50313.8594 - val_mae: 50313.8594
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49618.5039 - mae: 49618.5039 - val_loss: 50317.1680 - val_mae: 50317.1680
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49607.8516 - mae: 49607.8516 - val_loss: 50314.0273 - val_mae: 50314.0273
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49596.2539 - mae: 49596.2539 - val_loss: 50314.9492 - val_mae: 50314.9492
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49589.1602 - mae: 49589.1602 - val_loss: 50316.4453 - val_mae: 50316.4453
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49576.9453 - mae: 49576.9453 - val_loss: 50309.7070 - val_mae: 50309.7070
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49567.4883 - mae: 49567.4883 - val_loss: 50313.0977 - val_mae: 50313.0977
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49556.4961 - mae: 49556.4961 - val_loss: 50298.1133 - val_mae: 50298.1133
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49546.0938 - mae: 49546.0938 - val_loss: 50302.4492 - val_mae: 50302.4492
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49539.0273 - mae: 49539.0273 - val_loss: 50304.9609 - val_mae: 50304.9609
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49530.3555 - mae: 49530.3555 - val_loss: 50292.8711 - val_mae: 50292.8711
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49521.8477 - mae: 49521.8477 - val_loss: 50292.6523 - val_mae: 50292.6523
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49514.2422 - mae: 49514.2422 - val_loss: 50289.1055 - val_mae: 50289.1055
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49510.0078 - mae: 49510.0078 - val_loss: 50288.9453 - val_mae: 50288.9453
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49501.1758 - mae: 49501.1758 - val_loss: 50289.3398 - val_mae: 50289.3398
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49492.7188 - mae: 49492.7188 - val_loss: 50281.1445 - val_mae: 50281.1445
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49484.9609 - mae: 49484.9609 - val_loss: 50278.0547 - val_mae: 50278.0547
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49483.2188 - mae: 49483.2188 - val_loss: 50275.7227 - val_mae: 50275.7227
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49475.9062 - mae: 49475.9062 - val_loss: 50279.9023 - val_mae: 50279.9023
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49467.7734 - mae: 49467.7734 - val_loss: 50266.0977 - val_mae: 50266.0977
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49463.2188 - mae: 49463.2188 - val_loss: 50273.8359 - val_mae: 50273.8359
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49458.0664 - mae: 49458.0664 - val_loss: 50272.6172 - val_mae: 50272.6172
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49454.3711 - mae: 49454.3711 - val_loss: 50274.9336 - val_mae: 50274.9336
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49449.5352 - mae: 49449.5352 - val_loss: 50266.8281 - val_mae: 50266.8281
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49442.8359 - mae: 49442.8359 - val_loss: 50265.8320 - val_mae: 50265.8320
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49438.6719 - mae: 49438.6719 - val_loss: 50267.7539 - val_mae: 50267.7539
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49435.0977 - mae: 49435.0977 - val_loss: 50266.4531 - val_mae: 50266.4531
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49429.9492 - mae: 49429.9492 - val_loss: 50265.6367 - val_mae: 50265.6367
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49430.3125 - mae: 49430.3125 - val_loss: 50261.0859 - val_mae: 50261.0859
Epoch 63/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49422.9219 - mae: 49422.9219 - val_loss: 50261.0898 - val_mae: 50261.0898
Epoch 64/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49416.8750 - mae: 49416.8750 - val_loss: 50263.2109 - val_mae: 50263.2109
Epoch 65/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49412.9102 - mae: 49412.9102 - val_loss: 50262.5430 - val_mae: 50262.5430
Epoch 66/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49410.7188 - mae: 49410.7188 - val_loss: 50264.9141 - val_mae: 50264.9141
Epoch 67/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49406.1523 - mae: 49406.1523 - val_loss: 50255.8086 - val_mae: 50255.8086
Epoch 68/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49399.7617 - mae: 49399.7617 - val_loss: 50266.1641 - val_mae: 50266.1641
Epoch 69/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49396.7461 - mae: 49396.7461 - val_loss: 50271.9336 - val_mae: 50271.9336
Epoch 70/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49396.6055 - mae: 49396.6055 - val_loss: 50276.6211 - val_mae: 50276.6211
Epoch 71/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49388.4492 - mae: 49388.4492 - val_loss: 50273.4844 - val_mae: 50273.4844
Epoch 72/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49386.0312 - mae: 49386.0312 - val_loss: 50275.4375 - val_mae: 50275.4375
Epoch 73/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49383.1484 - mae: 49383.1484 - val_loss: 50272.5195 - val_mae: 50272.5195
Epoch 74/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49377.1016 - mae: 49377.1016 - val_loss: 50276.5312 - val_mae: 50276.5312
Epoch 75/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49375.9805 - mae: 49375.9805 - val_loss: 50281.7969 - val_mae: 50281.7969
Epoch 76/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49369.6211 - mae: 49369.6211 - val_loss: 50278.2617 - val_mae: 50278.2617
Epoch 77/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49367.4062 - mae: 49367.4062 - val_loss: 50290.4570 - val_mae: 50290.4570

In [ ]:
%load_ext tensorboard

In [ ]:

model.summary()

from tensorflow.keras.utils import plot_model

plot_model(
    model, 
    to_file='model_architecture.png',
    show_shapes=True,
    show_layer_names=True,
    rankdir='TB', 
    expand_nested=True,
    dpi=96
)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 8,837 (34.52 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 5,892 (23.02 KB)

You must install graphviz (see instructions at https://graphviz.gitlab.io/download/) for `plot_model` to work.

In [28]:
test_loss,test_mae = model.evaluate(x_test,y_test)
print(f"Test mae : {test_mae}")

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50255.8086 - mae: 50255.8086
Test mae : 50255.80859375

In [29]:
model.save('regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.