In [1]:
%pip install tensorflow keras

Requirement already satisfied: tensorflow in c:\users\dhruv\desktop\dhruv\study\machine_learning\python\venv\lib\site-packages (2.20.0)
Requirement already satisfied: keras in c:\users\dhruv\desktop\dhruv\study\machine_learning\python\venv\lib\site-packages (3.13.1)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\dhruv\desktop\dhruv\study\machine_learning\python\venv\lib\site-packages (from tensorflow) (2.3.1)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\dhruv\desktop\dhruv\study\machine_learning\python\venv\lib\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in c:\users\dhruv\desktop\dhruv\study\machine_learning\python\venv\lib\site-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\dhruv\desktop\dhruv\study\machine_learning\python\venv\lib\site-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in c:\users\dhruv\desktop\dhruv\study\machine_learning\python\venv\lib\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\dhruv\desktop\dhruv\study\machine_learning\python\venv\lib\site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in c:\users\dhruv\desktop\dhruv\study\machine_learning\python\venv\lib\site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in c:\users\dhruv\desktop\dhruv\study\machine_learning\python\venv\lib\site-packages (from tensorflow) (25.0)
Requirement already satisfied: protobuf>=5.28.0 in c:\users\dhruv\desktop\dhruv\study\machine_learning\python\venv\lib\site-packages (from tensorflow) (6.33.1)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\dhruv\desktop\dhruv\study\machine_learning\python\venv\lib\site-packages (from tensorflow) (2.32.5)
Requirement already satisfied: setuptools in c:\users\dhruv\desktop\dhruv\study\machine_learning\python\venv\lib\site-packages (from tensorflow) (65.5.0)
Requirement already satisfied: six>=1.12.0 in c:\users\dhruv\desktop\dhruv\study\machine_learning\python\venv\lib\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\dhruv\desktop\dhruv\study\machine_learning\python\venv\lib\site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\users\dhruv\desktop\dhruv\study\machine_learning\python\venv\lib\site-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\dhruv\desktop\dhruv\study\machine_learning\python\venv\lib\site-packages (from tensorflow) (2.0.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\dhruv\desktop\dhruv\study\machine_learning\python\venv\lib\site-packages (from tensorflow) (1.76.0)
Requirement already satisfied: tensorboard~=2.20.0 in c:\users\dhruv\desktop\dhruv\study\machine_learning\python\venv\lib\site-packages (from tensorflow) (2.20.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\dhruv\desktop\dhruv\study\machine_learning\python\venv\lib\site-packages (from tensorflow) (2.3.5)
Requirement already satisfied: h5py>=3.11.0 in c:\users\dhruv\desktop\dhruv\study\machine_learning\python\venv\lib\site-packages (from tensorflow) (3.15.1)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in c:\users\dhruv\desktop\dhruv\study\machine_learning\python\venv\lib\site-packages (from tensorflow) (0.5.4)
Requirement already satisfied: rich in c:\users\dhruv\desktop\dhruv\study\machine_learning\python\venv\lib\site-packages (from keras) (14.3.1)
Requirement already satisfied: namex in c:\users\dhruv\desktop\dhruv\study\machine_learning\python\venv\lib\site-packages (from keras) (0.1.0)
Requirement already satisfied: optree in c:\users\dhruv\desktop\dhruv\study\machine_learning\python\venv\lib\site-packages (from keras) (0.18.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\dhruv\desktop\dhruv\study\machine_learning\python\venv\lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.46.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\dhruv\desktop\dhruv\study\machine_learning\python\venv\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\dhruv\desktop\dhruv\study\machine_learning\python\venv\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\dhruv\desktop\dhruv\study\machine_learning\python\venv\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\dhruv\desktop\dhruv\study\machine_learning\python\venv\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2025.11.12)
Requirement already satisfied: markdown>=2.6.8 in c:\users\dhruv\desktop\dhruv\study\machine_learning\python\venv\lib\site-packages (from tensorboard~=2.20.0->tensorflow) (3.10.1)
Requirement already satisfied: pillow in c:\users\dhruv\desktop\dhruv\study\machine_learning\python\venv\lib\site-packages (from tensorboard~=2.20.0->tensorflow) (12.0.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in c:\users\dhruv\desktop\dhruv\study\machine_learning\python\venv\lib\site-packages (from tensorboard~=2.20.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\dhruv\desktop\dhruv\study\machine_learning\python\venv\lib\site-packages (from tensorboard~=2.20.0->tensorflow) (3.1.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\dhruv\desktop\dhruv\study\machine_learning\python\venv\lib\site-packages (from rich->keras) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\dhruv\desktop\dhruv\study\machine_learning\python\venv\lib\site-packages (from rich->keras) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\dhruv\desktop\dhruv\study\machine_learning\python\venv\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras) (0.1.2)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\dhruv\desktop\dhruv\study\machine_learning\python\venv\lib\site-packages (from werkzeug>=1.0.1->tensorboard~=2.20.0->tensorflow) (3.0.3)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

# Feature Engineering

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('Churn_Modelling.csv')

In [4]:
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [5]:
%pip install tensorboard

Requirement already satisfied: tensorboard in c:\users\dhruv\desktop\dhruv\study\machine_learning\python\venv\lib\site-packages (2.20.0)
Requirement already satisfied: absl-py>=0.4 in c:\users\dhruv\desktop\dhruv\study\machine_learning\python\venv\lib\site-packages (from tensorboard) (2.3.1)
Requirement already satisfied: grpcio>=1.48.2 in c:\users\dhruv\desktop\dhruv\study\machine_learning\python\venv\lib\site-packages (from tensorboard) (1.76.0)
Requirement already satisfied: markdown>=2.6.8 in c:\users\dhruv\desktop\dhruv\study\machine_learning\python\venv\lib\site-packages (from tensorboard) (3.10.1)
Requirement already satisfied: numpy>=1.12.0 in c:\users\dhruv\desktop\dhruv\study\machine_learning\python\venv\lib\site-packages (from tensorboard) (2.3.5)
Requirement already satisfied: packaging in c:\users\dhruv\desktop\dhruv\study\machine_learning\python\venv\lib\site-packages (from tensorboard) (25.0)
Requirement already satisfied: pillow in c:\users\dhruv\desktop\dhruv\study\machine_learning\python\venv\lib\site-packages (from tensorboard) (12.0.0)
Requirement already satisfied: protobuf!=4.24.0,>=3.19.6 in c:\users\dhruv\desktop\dhruv\study\machine_learning\python\venv\lib\site-packages (from tensorboard) (6.33.1)
Requirement already satisfied: setuptools>=41.0.0 in c:\users\dhruv\desktop\dhruv\study\machine_learning\python\venv\lib\site-packages (from tensorboard) (65.5.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in c:\users\dhruv\desktop\dhruv\study\machine_learning\python\venv\lib\site-packages (from tensorboard) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\dhruv\desktop\dhruv\study\machine_learning\python\venv\lib\site-packages (from tensorboard) (3.1.3)
Requirement already satisfied: typing-extensions~=4.12 in c:\users\dhruv\desktop\dhruv\study\machine_learning\python\venv\lib\site-packages (from grpcio>=1.48.2->tensorboard) (4.15.0)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\dhruv\desktop\dhruv\study\machine_learning\python\venv\lib\site-packages (from werkzeug>=1.0.1->tensorboard) (3.0.3)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder

In [7]:
import pickle

In [8]:
df = df.drop(labels=['RowNumber','CustomerId','Surname'],axis=1)

In [9]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [10]:
label_encoder_gender = LabelEncoder()

In [11]:
df['Gender'] = label_encoder_gender.fit_transform(df['Gender'])

In [12]:
from sklearn.preprocessing import OneHotEncoder
onehot = OneHotEncoder(sparse_output=False)

In [13]:
geo_encoder = onehot.fit_transform(df[['Geography']])
geo_encoder

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]], shape=(10000, 3))

In [14]:
onehot.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [15]:
geo_encoded_df = pd.DataFrame(geo_encoder,columns=onehot.get_feature_names_out(['Geography']))

In [16]:
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [17]:
df = df.drop('Geography',axis=1)
df = pd.concat([df,geo_encoded_df],axis=1)

In [18]:
df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [19]:
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)
with open ('OneHotEncoder_Geography.pkl','wb') as file1:
    pickle.dump(onehot,file1)

In [20]:
#divide into dependent and independent features

In [21]:
X = df.drop('Exited',axis = 1)

In [22]:
Y = df['Exited']

In [23]:
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [24]:
with open('Scaler.pkl','wb') as file2:
    pickle.dump(scaler,file2)

# ANN Implementation

In [25]:
import tensorflow as tf

In [26]:
import numpy as np
import matplotlib.pyplot as plt

In [27]:
%matplotlib inline

In [28]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard

In [29]:
#build ANN model

In [30]:
model = Sequential([
    Dense(64,activation='relu',input_shape=(x_train.shape[1],)), # HL 1 connected with I/P layer
    Dense(32,activation='relu'),# HL 2
    Dense(1,activation='sigmoid') # O/P layer
]
)

c:\Users\DHRUV\Desktop\Dhruv\Study\Machine_Learning\Python\venv\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [31]:
import warnings 
warnings.filterwarnings('ignore')

In [32]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [33]:
import tensorflow
opt = tensorflow.keras.optimizers.Adam(learning_rate = 0.01)
loss = tensorflow.keras.losses.BinaryCrossentropy()
loss

In [34]:
# compile the model
model.compile(optimizer=opt, loss='binary_crossentropy',metrics=['accuracy'])

In [35]:
# setup the tensorboard
import datetime
log_dir = 'log/fit/' + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback = TensorBoard(log_dir,histogram_freq=1)

In [36]:
# Set up early stopping
early_stopping_callbacks = EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [37]:
history = model.fit(
    x_train,y_train,validation_data = (x_test,y_test),epochs=100,
    callbacks=[tensorflow_callback,early_stopping_callbacks]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8310 - loss: 0.4011 - val_accuracy: 0.8560 - val_loss: 0.3684
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8569 - loss: 0.3575 - val_accuracy: 0.8580 - val_loss: 0.3405
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8543 - loss: 0.3493 - val_accuracy: 0.8630 - val_loss: 0.3452
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8591 - loss: 0.3460 - val_accuracy: 0.8605 - val_loss: 0.3368
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8605 - loss: 0.3441 - val_accuracy: 0.8575 - val_loss: 0.3544
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8605 - loss: 0.3388 - val_accuracy: 0.8625 - val_loss: 0.3401
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8609 - loss: 0.3360 - val_accuracy: 0.8595 - val_loss: 0.3467
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8606 - loss: 0.3385 - val_accuracy: 0.8560 - val_loss: 0.3390
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8626 - loss: 0.3338 - val_accuracy: 0.8570 - val_loss: 0.3442
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8635 - loss: 0.3289 - val_accuracy: 0.8655 - val_loss: 0.3500
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8624 - loss: 0.3289 - val_accuracy: 0.8600 - val_loss: 0.3504
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8674 - loss: 0.3247 - val_accuracy: 0.8580 - val_loss: 0.3489
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8660 - loss: 0.3239 - val_accuracy: 0.8595 - val_loss: 0.3411
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8679 - loss: 0.3233 - val_accuracy: 0.8660 - val_loss: 0.3394

In [38]:
model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [39]:
# Load TensorBoard Extension
%load_ext tensorboard

In [44]:
%tensorboard --logdir log/fit --port 6006

Reusing TensorBoard on port 6006 (pid 18920), started 0:00:06 ago. (Use '!kill 18920' to kill it.)

In [41]:
!kill 6052

'kill' is not recognized as an internal or external command,
operable program or batch file.

In [ ]:
#load the pickle files