In [33]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

In [34]:
model = load_model('model.h5')

# load scaler and encoder
with open('label_encoder_gender.pkl','rb') as file:
    label_encoder_gender = pickle.load(file)
with open('Scaler.pkl','rb') as sc:
    scaler = pickle.load(sc)
with open('OneHotEncoder_Geography.pkl','rb') as f:
    Geo = pickle.load(f)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [35]:
input_data_3 = {
    "CreditScore": 810,
    "Geography": "Spain",
    "Gender": "Male",
    "Age": 29,
    "Tenure": 8,
    "Balance": 0.0,
    "NumOfProducts": 2,
    "HasCrCard": 1,
    "IsActiveMember": 1,
    "EstimatedSalary": 98000.00
}

In [36]:
input_data_1 = {
    "CreditScore": 735,
    "Geography": "Germany",
    "Gender": "Male",
    "Age": 36,
    "Tenure": 6,
    "Balance": 98765.45,
    "NumOfProducts": 2,
    "HasCrCard": 1,
    "IsActiveMember": 1,
    "EstimatedSalary": 125000.00
}

In [37]:
input_data_2 = {
    "CreditScore": 420,
    "Geography": "France",
    "Gender": "Female",
    "Age": 54,
    "Tenure": 1,
    "Balance": 145000.75,
    "NumOfProducts": 1,
    "HasCrCard": 0,
    "IsActiveMember": 0,
    "EstimatedSalary": 62000.50
}

In [38]:
geo_encoded = Geo.transform([[input_data_2['Geography']]])

c:\Users\DHRUV\Desktop\Dhruv\Study\Machine_Learning\Python\venv\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

In [39]:
geo_encoded

array([[1., 0., 0.]])

In [40]:
geo_encoded_df = pd.DataFrame(geo_encoded,columns=Geo.get_feature_names_out())

In [41]:
geo_encoded_df

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [42]:
df1 = pd.DataFrame([input_data_2])

In [43]:
df1
df1 = df1.drop('Geography',axis=1)

In [44]:
df1 = pd.concat([df1,geo_encoded_df],axis=1)

In [45]:
df1

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,420,Female,54,1,145000.75,1,0,0,62000.5,1.0,0.0,0.0

In [46]:
df1['Gender'] = label_encoder_gender.transform(df1['Gender'])
df1

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,420,0,54,1,145000.75,1,0,0,62000.5,1.0,0.0,0.0

In [47]:
input_scaled = scaler.transform(df1)

In [48]:
input_scaled

array([[-2.40397675, -1.09499335,  1.4358077 , -1.38944225,  1.10313493,
        -0.91668767, -1.54035103, -1.02583358, -0.66818347,  1.00150113,
        -0.57946723, -0.57638802]])

In [49]:
prediction = model.predict(input_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

In [50]:
prediction_proba = prediction[0][0]

In [51]:
prediction_proba

np.float32(0.8279759)

In [52]:
if prediction_proba < 0.5:
    print('0')
else:
    print('1')

1